# Generated by Django 5.0.6 on 2024-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminandagent",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
