# Generated by Django 5.0.6 on 2024-05-28 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="Chat_app.newuser",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
