# Generated by Django 5.0.6 on 2024-05-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat_app", "0003_alter_room_agent_alter_room_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Chat_app.newuser",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
